# CMake generated Testfile for 
# Source directory: /home/carlos/Instaladores/ParadisEO-2.0/moeo/test
# Build directory: /home/carlos/Instaladores/ParadisEO-2.0/build/moeo/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(t-moeo "t-moeo")
add_test(t-moeoBitVector "t-moeoBitVector")
add_test(t-moeoRealVector "t-moeoRealVector")
add_test(t-moeoUnboundedArchive "t-moeoUnboundedArchive")
add_test(t-moeoParetoObjectiveVectorComparator "t-moeoParetoObjectiveVectorComparator")
add_test(t-moeoStrictObjectiveVectorComparator "t-moeoStrictObjectiveVectorComparator")
add_test(t-moeoWeakObjectiveVectorComparator "t-moeoWeakObjectiveVectorComparator")
add_test(t-moeoEpsilonObjectiveVectorComparator "t-moeoEpsilonObjectiveVectorComparator")
add_test(t-moeoAchievementFitnessAssignment "t-moeoAchievementFitnessAssignment")
add_test(t-moeoExpBinaryIndicatorBasedFitnessAssignment "t-moeoExpBinaryIndicatorBasedFitnessAssignment")
add_test(t-moeoCrowdingDiversityAssignment "t-moeoCrowdingDiversityAssignment")
add_test(t-moeoSharingDiversityAssignment "t-moeoSharingDiversityAssignment")
add_test(t-moeoIBEA "t-moeoIBEA")
add_test(t-moeoNSGA "t-moeoNSGA")
add_test(t-moeoNSGAII "t-moeoNSGAII")
add_test(t-moeoSEEA "t-moeoSEEA")
add_test(t-moeoMax3Obj "t-moeoMax3Obj")
add_test(t-moeoEasyEA "t-moeoEasyEA")
add_test(t-moeoDominanceCountFitnessAssignment "t-moeoDominanceCountFitnessAssignment")
add_test(t-moeoDominanceRankFitnessAssignment "t-moeoDominanceRankFitnessAssignment")
add_test(t-moeoDominanceCountRankingFitnessAssignment "t-moeoDominanceCountRankingFitnessAssignment")
add_test(t-moeoDominanceDepthFitnessAssignment "t-moeoDominanceDepthFitnessAssignment")
add_test(t-moeoNearestNeighborDiversityAssignment "t-moeoNearestNeighborDiversityAssignment")
add_test(t-moeoSPEA2Archive "t-moeoSPEA2Archive")
add_test(t-moeoSPEA2 "t-moeoSPEA2")
add_test(t-moeoDominanceMatrix "t-moeoDominanceMatrix")
add_test(t-moeoVecVsVecAdditiveEpsilonBinaryMetric "t-moeoVecVsVecAdditiveEpsilonBinaryMetric")
add_test(t-moeoVecVsVecMultiplicativeEpsilonBinaryMetric "t-moeoVecVsVecMultiplicativeEpsilonBinaryMetric")
add_test(t-moeoHyperVolumeMetric "t-moeoHyperVolumeMetric")
add_test(t-moeoHyperVolumeDifferenceMetric "t-moeoHyperVolumeDifferenceMetric")
add_test(t-moeoIntVector "t-moeoIntVector")
add_test(t-moeoImprOnlyBoundedArchive "t-moeoImprOnlyBoundedArchive")
add_test(t-moeoFitDivBoundedArchive "t-moeoFitDivBoundedArchive")
add_test(t-moeoDetArchiveSelect "t-moeoDetArchiveSelect")
add_test(t-moeoASEEA "t-moeoASEEA")
add_test(t-moeoEpsilonHyperboxArchive "t-moeoEpsilonHyperboxArchive")
add_test(t-moeoAggregationFitnessAssignment "t-moeoAggregationFitnessAssignment")
add_test(t-moeoConstraintFitnessAssignment "t-moeoConstraintFitnessAssignment")
add_test(t-moeoChebyshevMetric "t-moeoChebyshevMetric")
add_test(t-moeoChebyshevOrientedMetric "t-moeoChebyshevOrientedMetric")
add_test(t-moeoASFAMetric "t-moeoASFAMetric")
add_test(t-moeoASFAOrMetric "t-moeoASFAOrMetric")
add_test(t-moeoExhaustiveNeighborhoodExplorer "t-moeoExhaustiveNeighborhoodExplorer")
add_test(t-moeoFirstImprovingNeighborhoodExplorer "t-moeoFirstImprovingNeighborhoodExplorer")
add_test(t-moeoSimpleSubNeighborhoodExplorer "t-moeoSimpleSubNeighborhoodExplorer")
add_test(t-moeoNoDesimprovingNeighborhoodExplorer "t-moeoNoDesimprovingNeighborhoodExplorer")
add_test(t-moeoPLS1 "t-moeoPLS1")
add_test(t-moeoPLS2 "t-moeoPLS2")
add_test(t-moeoExhaustiveUnvisitedSelect "t-moeoExhaustiveUnvisitedSelect")
add_test(t-moeoNumberUnvisitedSelect "t-moeoNumberUnvisitedSelect")
add_test(t-moeoDMLSMonOp "t-moeoDMLSMonOp")
add_test(t-moeoDMLSGenUpdater "t-moeoDMLSGenUpdater")
add_test(t-moeo2DMinHypervolumeArchive "t-moeo2DMinHypervolumeArchive")
