# CMake generated Testfile for 
# Source directory: /home/carlos/Instaladores/ParadisEO-2.0/eo/test
# Build directory: /home/carlos/Instaladores/ParadisEO-2.0/build/eo/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(t-eofitness "t-eofitness")
add_test(t-eoRandom "t-eoRandom")
add_test(t-eobin "t-eobin")
add_test(t-eoVirus "t-eoVirus")
add_test(t-MGE "t-MGE")
add_test(t-MGE1bit "t-MGE1bit")
add_test(t-MGE-control "t-MGE-control")
add_test(t-eoStateAndParser "t-eoStateAndParser")
add_test(t-eoCheckpointing "t-eoCheckpointing")
add_test(t-eoSSGA "t-eoSSGA")
add_test(t-eoExternalEO "t-eoExternalEO")
add_test(t-eoSymreg "t-eoSymreg")
add_test(t-eo "t-eo")
add_test(t-eoReplacement "t-eoReplacement")
add_test(t-eoSelect "t-eoSelect")
add_test(t-eoGenOp "t-eoGenOp")
add_test(t-eoGA "t-eoGA")
add_test(t-eoReal "t-eoReal")
add_test(t-eoVector "t-eoVector")
add_test(t-eoESAll "t-eoESAll")
add_test(t-eoPBIL "t-eoPBIL")
add_test(t-eoFitnessAssembled "t-eoFitnessAssembled")
add_test(t-eoFitnessAssembledEA "t-eoFitnessAssembledEA")
add_test(t-eoRoulette "t-eoRoulette")
add_test(t-eoSharing "t-eoSharing")
add_test(t-eoCMAES "t-eoCMAES")
add_test(t-eoSecondsElapsedContinue "t-eoSecondsElapsedContinue")
add_test(t-eoRNG "t-eoRNG")
add_test(t-eoEasyPSO "t-eoEasyPSO")
add_test(t-eoInt "t-eoInt")
add_test(t-eoInitPermutation "t-eoInitPermutation")
add_test(t-eoSwapMutation "t-eoSwapMutation")
add_test(t-eoShiftMutation "t-eoShiftMutation")
add_test(t-eoTwoOptMutation "t-eoTwoOptMutation")
add_test(t-eoRingTopology "t-eoRingTopology")
add_test(t-eoSyncEasyPSO "t-eoSyncEasyPSO")
add_test(t-eoOrderXover "t-eoOrderXover")
add_test(t-eoExtendedVelocity "t-eoExtendedVelocity")
add_test(t-eoLogger "t-eoLogger")
add_test(t-eoParallel "t-eoParallel")
add_test(t-eoParser "t-eoParser")
